require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

RSpec/NestedGroups:
  Max: 4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 18

Metrics/AbcSize:
  Max: 18
