name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql user: postgres
          postgresql password: password

      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.75.0
        with:
          bundler-cache: true
          # Arbitrary string that will be added to the cache key of the bundler cache. Set or change it if you need to invalidate the cache.
          #cache-version: # optional, default is 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.0.1

      - name: Setup DB
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_KEY }}
        run:
          bin/rails db:setup

      - name: Yarn
        run: |
          sudo npm install -g yarn
          yarn install

      - name: Run Tests
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_KEY }}
        run:
          bin/rails spec

      - name: Run Lint
        run: |
          bundle exec rubocop
          bundle exec erblint --lint-all
